=== WollMux/formbox/xml/form.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.muenchen.de/formbox/forms" elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.muenchen.de/formbox/forms">
   <xsd:element name="form" type="formType"></xsd:element>

   <xsd:complexType name="formType">
   	<xsd:sequence>
   		<xsd:element name="title" type="xsd:string" maxOccurs="1"
   			minOccurs="0">
   		</xsd:element>
   		<xsd:element name="controls" type="controlsType" maxOccurs="1" minOccurs="0"></xsd:element>
   	</xsd:sequence>
   </xsd:complexType>

   <xsd:complexType name="tabsType">
   	<xsd:complexContent>
   		<xsd:extension base="controlType">
   			<xsd:sequence>
   				<xsd:element name="pages" type="tabPagesType"
   				 maxOccurs="1" minOccurs="1">
   				</xsd:element>
   			</xsd:sequence>
   		</xsd:extension>
   	</xsd:complexContent>
   </xsd:complexType>

   <xsd:complexType name="controlsType">
   	<xsd:choice maxOccurs="unbounded" minOccurs="0">
   		<xsd:element name="button" type="buttonType"></xsd:element>
   		<xsd:element name="checkbox" type="checkboxType"></xsd:element>
   		<xsd:element name="combobox" type="comboBoxType"></xsd:element>
   		<xsd:element name="hbox" type="hboxType"></xsd:element>
   		<xsd:element name="label" type="labelType"></xsd:element>
   		<xsd:element name="separator" type="separatorType"></xsd:element>
   		<xsd:element name="tabs" type="tabsType"></xsd:element>
   		<xsd:element name="textarea" type="textareaType"></xsd:element>
   		<xsd:element name="textfield" type="textfieldType"></xsd:element>
		<xsd:element name="option" type="optionType"></xsd:element>
   	</xsd:choice>
   </xsd:complexType>

	<xsd:complexType name="optionType">
		<xsd:sequence>
			<xsd:element name="value" type="xsd:string" maxOccurs="unbounded" minOccurs="0"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>

   <xsd:complexType name="tabType">
			<xsd:sequence>
				<xsd:element name="title" type="xsd:string"></xsd:element>
				<xsd:element name="tooltip" type="xsd:string"
					maxOccurs="1" minOccurs="0">
				</xsd:element>
				<xsd:element name="controls" type="controlsType"
					maxOccurs="1" minOccurs="0">
				</xsd:element>
			</xsd:sequence>
   </xsd:complexType>

	<xsd:complexType name="comboBoxType">
		<xsd:complexContent>
			<xsd:extension base="labelType">
				<xsd:choice>
					<xsd:sequence>
						<xsd:element name="editable" type="xsd:boolean"></xsd:element>
						<xsd:element name="option" type="optionType" maxOccurs="unbounded" minOccurs="0"></xsd:element>
					</xsd:sequence>
				</xsd:choice>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

   <xsd:complexType name="textfieldType">
   	<xsd:complexContent>
   		<xsd:extension base="labelType">
   			<xsd:sequence>
   				<xsd:element name="tip" type="xsd:string"
   					maxOccurs="1" minOccurs="0">
   				</xsd:element>
   				<xsd:element name="readonly" type="xsd:boolean"
   					maxOccurs="1" minOccurs="0">
   				</xsd:element>
   				<xsd:element name="autofill" type="xsd:string" maxOccurs="1" minOccurs="0"></xsd:element>
   			</xsd:sequence>
   		</xsd:extension>
   	</xsd:complexContent>
  </xsd:complexType>

   <xsd:complexType name="checkboxType">
   	<xsd:complexContent>
   		<xsd:extension base="labelType"></xsd:extension>
   	</xsd:complexContent>
   </xsd:complexType>

   <xsd:complexType name="textareaType">
   	<xsd:complexContent>
   		<xsd:extension base="textfieldType">
   			<xsd:sequence>
   				<xsd:element name="lines" type="xsd:int"></xsd:element>
   				<xsd:element name="wrap" type="xsd:boolean"></xsd:element>
   			</xsd:sequence>
   		</xsd:extension>
   	</xsd:complexContent>
   </xsd:complexType>

   <xsd:complexType name="controlType" abstract="true">
    	<xsd:sequence>
    		<xsd:element name="id" type="xsd:string"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

   <xsd:complexType name="labelType">
   	<xsd:complexContent>
   		<xsd:extension base="controlType">
   		  <xsd:sequence>
          <xsd:element name="title" type="xsd:string"
            maxOccurs="1" minOccurs="1">
          </xsd:element>
   		  </xsd:sequence>
   		</xsd:extension>
   	</xsd:complexContent>
   </xsd:complexType>

   <xsd:complexType name="buttonType">
   	<xsd:complexContent>
   		<xsd:extension base="labelType">
   			<xsd:sequence>
   				<xsd:element name="action" type="xsd:string"></xsd:element>
   				<xsd:element name="value" type="xsd:string"></xsd:element>
   				<xsd:element name="disabled" type="xsd:boolean" default="false" maxOccurs="1" minOccurs="0"></xsd:element>
   			</xsd:sequence>
   		</xsd:extension>
   	</xsd:complexContent>
   </xsd:complexType>

   <xsd:complexType name="separatorType">
   	<xsd:complexContent>
   		<xsd:extension base="controlType"></xsd:extension>
   	</xsd:complexContent>
   </xsd:complexType>

   <xsd:complexType name="hboxType">
   	<xsd:complexContent>
   		<xsd:extension base="containerType"></xsd:extension>
   	</xsd:complexContent>
   </xsd:complexType>

   <xsd:complexType name="containerType" abstract="true">
   	<xsd:complexContent>
   		<xsd:extension base="controlType">
   			<xsd:sequence>
   				<xsd:element name="controls" type="controlsType"></xsd:element>
   			</xsd:sequence>
   		</xsd:extension>
   	</xsd:complexContent>
   </xsd:complexType>

   <xsd:complexType name="tabPagesType">
    <xsd:sequence>
     <xsd:element name="tab" type="tabType" maxOccurs="unbounded" minOccurs="1"></xsd:element>
    </xsd:sequence>
   </xsd:complexType>
</xsd:schema>

=== WollMux/formbox/xml/form.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE xml>
<form
  xmlns="http://www.muenchen.de/formbox/forms"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.muenchen.de/formbox/forms http://www.muenchen.de/formbox/form.xsd">
  <title>Title</title>
  <controls>
    <label>
      <id>Label1</id>
      <title>Label 1</title>
    </label>
    <label>
      <id>Label2</id>
      <title>Label 2</title>
    </label>
    <tabs>
      <id>tab1</id>
      <pages>
        <tab>
          <title>Tab 1</title>
          <tooltip></tooltip>
          <controls>
            <combobox>
              <id>combobox1</id>
              <title>Combobox 1</title>
              <editable>true</editable>
              <option>
                <value>Item1</value>
              </option>
              <option>
                <value>Item2</value>
              </option>
              <option>
                <value>Item3</value>
              </option>
              <option>
                <value>Item4</value>
              </option>
            </combobox>
            <label>
              <id>label1</id>
              <title>Label1</title>
            </label>
            <textfield>
              <id>textfeld1</id>
              <title>Eingabefeld</title>
              <tip></tip>
              <readonly>false</readonly>
              <autofill>Text</autofill>
            </textfield>
          </controls>
        </tab>
        <tab>
          <title>Tab 2</title>
          <controls>
            <checkbox>
              <id>checkbox1</id>
              <label>Checkbox 1</label>
            </checkbox>
            <checkbox>
              <id>checkbox2</id>
              <label>Checkbox 1</label>
            </checkbox>
            <separator>
              <id>separator1</id>
            </separator>
            <hbox>
              <id>hbox1</id>
              <controls>
                <button>
                  <id>button1</id>
                  <label>Button 1</label>
                  <action>openTemplate</action>
                  <value>fragId</value>
                </button>
                <button>
                  <id>button2</id>
                  <label>Button 2</label>
                  <action>openExt</action>
                  <value>explorer.exe</value>
                  <disabled>true</disabled>
                </button>
              </controls>
            </hbox>
          </controls>
        </tab>
      </pages>
    </tabs>
  </controls>
</form>
